### ISSUE TITLE
wd and ft for goem1240 contain replacement characters

### ISSUE THREAD

**Issue by xrotwang** [DoReCo/doreco#9]
The word form `wd` and text `tx` fields in `wd.csv` and `ph.csv` for `goem1240` contain lots of replacement characters (�) hinting at a wrong encoding used to include the data in the CSV files.

**Comment by LuPaschen** [comment]
This was a known issue and should have been fixed with version 1.1. We are investigating what went wrong, and will provide corrected files with the next update.
